# Generated by Django 3.2.7 on 2021-09-23 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='as_file',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='as_url',
        ),
    ]
