# Generated by Django 3.2.7 on 2021-09-18 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_auto_20210915_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='co_owners',
            field=models.ManyToManyField(blank=True, related_name='co_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
